// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "VidSnapr-WWDC24-Ikmal-Azman",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "VidSnapr-WWDC24-Ikmal-Azman",
            targets: ["AppModule"],
            bundleIdentifier: "com.esikmalazman.VidSnapr",
            teamIdentifier: "66846BKCQ4",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .camera),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "App need access to microphone to capture audio from recording video"),
                .photoLibrary(purposeString: "App need access to photo library to save captured image and access video files"),
                .camera(purposeString: "App need access to capture video from your device"),
                .fileAccess(.userSelectedFiles, mode: .readOnly),
                .fileAccess(.downloadsFolder, mode: .readOnly)
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)